### ISSUE TITLE
Feature request: Button or shortcut to editing Klipper configuration file

### ISSUE THREAD

**Issue by ghost** [thelastWallE/OctoprintKlipperPlugin#19]
Hi!

Currently to edit klipper configuration file (printer.cfg) i need to first open Octoprint settings which opens slowly, then Octoklipper settings and after that select Klipper configuration. Sometimes it’s frustrating if you have to edit it many times in a short time, ie. when testing or doing calbrations etc.

Is it possible to add button or shortcut to main page or to Klipper tab that open printer.cfg with a single click?

**Comment by thelastWallE** [comment]
I just saw that Octolapse has something like that. A shortcut to the settings-dialog of the plugin. This would be sufficient?
I will look into it. Seems like octolapse has a js function for this button.
![Screenshot 2021-01-11 142806](https://user-images.githubusercontent.com/12502210/104188566-b6a34100-5419-11eb-9f55-8a75bb629f71.jpg)

@AliceGrey Can you assign me to this issue?

**Comment by thelastWallE** [comment]
update: i have it almost ready. Just some testing with the new access settings of octoprint.
i took for now the same icon as octolapse but i think i write it just as a link like "printer.cfg".
