### ISSUE TITLE
Add log path entry to config

### ISSUE THREAD

**Issue by lcha78** [thelastWallE/OctoprintKlipperPlugin#2]
Could you merge commit https://github.com/schnello/OctoprintKlipperPlugin/commit/045943c5c298a8438d380fa99f36b36938625bc3
from schnello.
Configuring logPath is essentiel when octoprint is used in a docker container
Thanks

**Comment by AliceGrey** [comment]
Done!
Resolved by https://github.com/AliceGrey/OctoprintKlipperPlugin/commit/0141b5e130395bab95fe4e064e051cefcbae4551

Opening new Issue for this config also lacking validation ;)

**Comment by lcha78** [comment]
Thanks ! It's working
