### ISSUE TITLE
No performance graph on Octoprint 1.5.0

### ISSUE THREAD

**Issue by chromoxdor** [thelastWallE/OctoprintKlipperPlugin#21]
About your environment:
 - Distribution version. octopi: 0.17.0 on Raspberry pi 3 a+
 - Octoprint version: 1.5.0

- An OctoPrint log file. You can access and download it in the OctoPrint settings under the "Logging" menu entry.
[octoprint.log](https://github.com/AliceGrey/OctoprintKlipperPlugin/files/5629327/octoprint.log)

Since the update of Octoprint or Python (2->3) the "Performance Graph" doesn´t work anymore.
The message in the graph: No relevant data available in "/tmp/klippy.log"

Tested it with an old klippy.log and a new one with same results....

**Comment by kamahat** [comment]
I'm using Octopi 0.17.0 & Octoprint 1.5.1 and i've got the same issue "No relevant data available in "/tmp/klippy.log""

The right on the file  looks good : 
3328 -rw-r--r--  1 pi   pi   3400698 Dec  6 11:26 klippy.log
  24 -rw-r--r--  1 pi   pi     22784 Dec  5 21:17 klippy.log.2020-12-05
