### ISSUE TITLE
Plugin currently allows the user to set any string of characters to be their log file without any validation or sanity checking.

### ISSUE THREAD

**Issue by AliceGrey** [thelastWallE/OctoprintKlipperPlugin#3]
Plugin currently allows the user to set any string of characters to be their log file without any validation or sanity checking.

Steps to re-create:
Open Octoprint Settings
Select OctoKlipper
Type in anything for klipper log path or just delete it entirely
Hit save

**Comment by thelastWallE** [comment]
For now i have made it so that the warning popup would trigger when the log file would be needed.
This is only the case on the dialog for the "Performance Graph".
