### ISSUE TITLE
Not working with Octopi 0.18.0

### ISSUE THREAD

**Issue by olivierD-FR** [thelastWallE/OctoprintKlipperPlugin#34]
Octopi 0.18.0 / Octoprint 1.5.3 / Python 3.73

Hello- I can install the plug in and it reads the status from the printer but cannot add macros nor vizualise the config. It used to work perfectly with previous Octopi image. Any idea ?

Thanks !

**Comment by thelastWallE** [comment]
I/We need more information here.

You had me to go using my only sdcard, for now, to flash OctoPi 0.18.0 on it and try it myself.
I installed it. Updated to 1.5.3 OctoPrint. Got my backup in. And installed klipper. With this https://www.klipper3d.org/Installation.html And all was fine. Even before installing klipper the macros where all fine
Before i had copied the printer.cfg on /home/pi/printer.cfg, there was shown an "empty" textfield on the OctoKlipper config tab.
The command was this: `cp ~/klipper/config/example-cartesian.cfg ~/printer.cfg` You need to make sure you are in the home/pi/ directory atm.

PS. i had backuped my sdcard before this. And i also had a bottle of wine during this. so it was relatively easy to install this even with some wine. :D

**Comment by thelastWallE** [comment]
I have copied my backuped printer.cfg over the copied default one after this.
Also you need to restart the system to get octoklipper to look for the new file(cache thing from the browser).

**Comment by endurance1968** [comment]
I am using V18 as well - works.
