### ISSUE TITLE
Klipper configuration file is no more loaded in octoklipper settings.

### ISSUE THREAD

**Issue by lcha78** [thelastWallE/OctoprintKlipperPlugin#4]
Klipper configuration file is no more loaded in octoklipper settings.
It was working in 0.3.0

Since you rename path to configpath, I think that this line (26) is the problem in OctoprintKlipperPlugin/octoprint_klipper/templates/klipper_settings.jinja2 :
 "<input type="text" class="input-block-level" data-bind="value: settings.settings.plugins.klipper.configuration.path">       "
 should be
" <input type="text" class="input-block-level" data-bind="value: settings.settings.plugins.klipper.configuration.configpath">  "

**Comment by AliceGrey** [comment]
@lcha78 Could you test the PR and let me know if that resolves the issue?

**Comment by MoJo2600** [comment]
I can confirm that the configuration is shown in the PR. I have my configuration in ~/printer.cfg and I can see it on the settings page.

**Comment by AliceGrey** [comment]
Thank you!

**Comment by MoJo2600** [comment]
Buuut.. there seems to be another issue. If I save the configuration the files gets truncated and is then empty. I'm trying to figure out whats wrong.
