### ISSUE TITLE
Option to not reload when config changed

### ISSUE THREAD

**Issue by mpalm0508** [thelastWallE/OctoprintKlipperPlugin#40]
I would be nice to have an option to not automatically reload when modifying the config.  There are times when I either want to review or make changes to take effect on the next print.  Right now if you modify the config while printing everything gets reset.  

I would think just another option on under "Configuration reload command" to be none.  This will require a manual restart later.  

Thanks
Mike

**Comment by thelastWallE** [comment]
Will try to get this in today.

**Comment by thelastWallE** [comment]
closed with 0.3.6
