### ISSUE TITLE
Broken again in 0.3.7.1

### ISSUE THREAD

**Issue by rstanislav** [thelastWallE/OctoprintKlipperPlugin#43]
Broken again in 0.3.7.1

_Originally posted by @rstanislav in https://github.com/thelastWallE/OctoprintKlipperPlugin/issues/41#issuecomment-813065448_

**Comment by SelfDestructor** [comment]
Can confirm, unable to save the config file after updating to 3.7.1.

**Comment by 3v0k** [comment]
yup i can't save  config after updating 3.7.1 
edit: same problem after reinstall klipper in ssh

**Comment by SelfDestructor** [comment]
Looks like @thelastWallE got a fix up already! Will try it once my printer is done printing.

https://github.com/thelastWallE/OctoprintKlipperPlugin/releases/tag/0.3.7.2

**Comment by 3v0k** [comment]
thanks @SelfDestructor ^^
 it's works now (release candidate for update)

**Comment by thelastWallE** [comment]
Had changed too much for the fix of duplicate sections. And the parsing check was only true if you had duplicate sections in the file. Sry for that.

fixed in https://github.com/thelastWallE/OctoprintKlipperPlugin/releases/tag/0.3.7.2
