### ISSUE TITLE
[Feature Request] File explorer for custom .cfg file

### ISSUE THREAD

**Issue by NovaViper** [thelastWallE/OctoprintKlipperPlugin#46]
Hi! I've just come from Fluidd and I'm wondering if OctoKlipper could add in support for the ability to edit klipper configuration files that are not under `printer.cfg`. In my case, I have a `printer.cfg` file that loads in subfiles like `machine.cfg` and `macro.cfg` where `machine.cfg` has all of my machine definitions and `macro.cfg` has all of my macro definitions. In Fluidd, it shows a file explorer that shows the contents of my klipper_config folder like the following screenshot

![image](https://user-images.githubusercontent.com/7191115/113913719-43a03100-97a2-11eb-9593-5c3e6fb68ae3.png)

**Comment by thelastWallE** [comment]
I will work on that. But i need a little bit of researching of the work with ace editor. But i have a plan generally already in my head.

**Comment by NovaViper** [comment]
> I will work on that. But i need a little bit of researching of the work with ace editor. But i have a plan generally already in my head.

Any progress on it? I don't mind giving any experimental stuff a try!

**Comment by thelastWallE** [comment]
Unfortunately i don't have much time atm. Wife is sick and i need to care for our two children and two dogs. I started on something but it is not useable at all.

**Comment by NovaViper** [comment]
Oh no! I hope your family gets better! ❤️  Don't rush on it, I've been messing around with Marlin again (as my main printer started acting up and was trying to get that all fixed before switching back to Klipper)
