### ISSUE TITLE
Feature Request: Let the plugin know where to look for the config file(s)

### ISSUE THREAD

**Issue by mplogas** [thelastWallE/OctoprintKlipperPlugin#47]
Before submitting your issue please make sure to provide the following information 

About your environment:
 - OctoPi 0.18.0
 - Octoprint Version 1.5.3
 - [octoprint.log](https://github.com/thelastWallE/OctoprintKlipperPlugin/files/6281163/octoprint.log)

My Klipper files are located in a different subfolder (```/home/pi/klipper-cfg```) and split into various smaller files (see [here](https://github.com/mplogas/Klipper_SKR_PRO_TMC2209_Ender5)). When reloading the firmware, I get an error message, stating that the Klipper config file can not be found at the default location
``` Error: Klipper config file not found at: /home/pi/printer.cfg```

Is there a way to point the plugin to the config file directory? 
The error doesn't seem to affect printing, but the message keeps popping up with every restart.

**Comment by thelastWallE** [comment]
You should just need to change the path for the file in the settings to ~/klipper.cfg for this.
OctoKlipper is only letting you edit the main config file for now.

**Comment by mplogas** [comment]
Ok, thanks! My bad, I didn't see the option to set the path in the Basic settings.
