### ISSUE TITLE
Feature request - check input for offset

### ISSUE THREAD

**Issue by endurance1968** [thelastWallE/OctoprintKlipperPlugin#49]
Hi,

pretty simple request. Please validate the input for offset settings. Why? If you mix up comma and dot format klipper stopps working and your print is gone. And since e.g. in Germany we use , as digit seperator not a . you typically do it wrong if you not thinking twice, which is somehow anoying :( So a simple input validation would be great prior sending it to klipper.

**Comment by thelastWallE** [comment]
If you want to check this. It is on the release candidate 0.3.8rc5.
