### ISSUE TITLE
new release not work, blank page

### ISSUE THREAD

**Issue by luco85** [thelastWallE/OctoprintKlipperPlugin#52]
hi! i installed new update but now not work. When i open octoklipper i have a blank page. After a system reboot octoprint was in safe mode.  I tried to uninstall and reinstall but nothing change. 
Octoprint 1.6.0
Octopi 0.18
Reload last change and reload from file if pressed nothing appears

![Schermata 2021-05-08 alle 11 46 23](https://user-images.githubusercontent.com/68059403/117534807-45545300-aff3-11eb-9e28-14abe98137b0.png)

**Comment by thelastWallE** [comment]
Try to CTRL+F5 to get the uncached version from OctoPrint.
What browser are you using?
Can you me the octoprint.log or plugin_klipper_debug.log

**Comment by luco85** [comment]
safari 14.1, tried to reset cache but persist
with chrome it work!
before this release no issue  (only not saving after modify .cfg )

[octoprint.log](https://github.com/thelastWallE/OctoprintKlipperPlugin/files/6445976/octoprint.log)
[plugin_klipper_debug.log](https://github.com/thelastWallE/OctoprintKlipperPlugin/files/6445977/plugin_klipper_debug.log)

**Comment by thelastWallE** [comment]
Can you try this version with safari? 
Install with pluginmanager->get more->url option
https://github.com/thelastWallE/OctoprintKlipperPlugin/archive/refs/heads/devel.zip

**Comment by luco85** [comment]
same issue

**Comment by thelastWallE** [comment]
i will look into it again in 2hours. i think i discovered the problem but i am not at the computer atm.

**Comment by luco85** [comment]
No prob! Thanks for your time!

**Comment by thelastWallE** [comment]
Ok you can try https://github.com/thelastWallE/OctoprintKlipperPlugin/archive/refs/heads/testSafari.zip
Tomorrow i can test this with browserstack myself.

**Comment by luco85** [comment]
the issue persist in safari. with chrome it work

**Comment by wildchron** [comment]
Same issue here. Safari 14.0.3 on MacOS 11.2.3

**Comment by thelastWallE** [comment]
**I like that you try this version before i release this.**
https://github.com/thelastWallE/OctoprintKlipperPlugin/archive/refs/heads/master.zip

I tested it on safari, firefox and chrome. I think i fixed it.
In safari the whole settings dialog of octoprint looks odd.

**Comment by luco85** [comment]
Yep! It seems to be ok! After work i try all features and lets see

**Comment by wildchron** [comment]
Working for me! I should mention that I use UI Customizer plugin also.
