### ISSUE TITLE
No display Klipper Configuration

### ISSUE THREAD

**Issue by petitxef** [thelastWallE/OctoprintKlipperPlugin#54]
Hi!

First of all said I'm using Octoklipper 0.3.8.1, Octoprint 1.6.1, Octopi 0.18 on firefox 88.0.1 (also doesn't work on Chrome 90.0.4430.212)

Related on #52 issue, but after update 0.3.8.1 the klipper configuration doesn't shows:

![image](https://user-images.githubusercontent.com/25556673/117963016-2a018480-b320-11eb-8e5e-ff277e2c232f.png)

The others tabs, all correct.

**Comment by thelastWallE** [comment]
Please try version 0.3.8.2 https://github.com/thelastWallE/OctoprintKlipperPlugin/releases/tag/0.3.8.2
I did tested the new version with firefox yesterday but somehow i had a cached version.
Thanks for your patience.

**Comment by petitxef** [comment]
Thanks!

It's works now (firefox & Chrome)
![image](https://user-images.githubusercontent.com/25556673/117968597-a5fecb00-b326-11eb-8aa8-889bd178a3e3.png)

Thanks

**Comment by thelastWallE** [comment]
Is this UIcustomizer with the cyborg theme?
I don't have a scrollbar on the far right. the whole button area on top should stay there if you scroll down.

**Comment by petitxef** [comment]
yes, I've UIcustomizer with the cyborg theme

**Comment by thelastWallE** [comment]
i discovered the problem with the scrollbar.
I had for me in the settings of UIcustomizer following css:
```
body.UICResponsiveMode #settings_dialog_content {
	height: calc(100% - 35px);
	margin-right: -18px;
	margin-top: 50px;
	width: calc(100% - 15px);
}
```
This fixed the height of the settings tab.
I fix it with the next version.
Looks like this ![Screenshot 2021-05-13 213018](https://user-images.githubusercontent.com/12502210/118177038-763ce980-b432-11eb-9fa5-9503529326db.png)
As you can see the overflow is now deeper down the divs and the buttons are staying at the top.

**Comment by petitxef** [comment]
good! :)
