### ISSUE TITLE
Since plugin install - Strange behaviour in file view

### ISSUE THREAD

**Issue by pandel** [thelastWallE/OctoprintKlipperPlugin#62]
Hi!

OctoPrint 1.6.1
Python 3.7.3
OctoPi 0.18.0
OctoKlipper 0.3.8.3

Since I installed the plugin, I get strange effects in any file view. I attach a screenshot, as it is a little hard to explain.

<img width="1198" alt="Bildschirmfoto 2021-08-30 um 08 46 28" src="https://user-images.githubusercontent.com/12460002/131298789-644220f2-4619-4341-a718-9507bcb7edb3.png">

Regards,
Holger

**Comment by thelastWallE** [comment]
Hallo, brauche noch mehr Infos. 
Liste von installierten Plugins. 
Welcher Browser?

Problem eingrenzen/beheben:
1. Webseite komplett neuladen mit Strg+F5
2. Plugin temporär abschalten über den kleinen Schalter in der Pluginliste in der Pluginverwaltung.

Ich wüsste nicht wie Octoklipper diese Listen beeinflussen könnte, aber man weiß ja nie.

**Comment by pandel** [comment]
Hi!

Danke für die Denkanstöße :-) - daran, das Plugin zu deaktivieren, habe ich nicht gedacht. Das mache ich so gut wie nie. Es ist wohl in der Tat so, dass sich Octoprint so merkwürdig verhält, auch ohne dein Plugin.

Tut mir sehr leid, dich damit belästigt zu haben. Ansonsten ist dein Plugin nämlich wirklich super!

Bleib gesund, ich mache hier zu.
Gruß
Holger

**Comment by pandel** [comment]
Hi @thelastWallE !

Nur abschließend zur Info, ich habe das Problem gefunden: wenn in Octoprint der SD Karten Support eingeschaltet ist UND in der Klipper Konfiguration 'virtual_sdcard' eingeschaltet ist, dann führt das zu diesem unkontrollierten Unfug. Vielleicht wäre es gut, wenn OctoKlipper bei der Installation darauf hinweisen würde :-)

Ich habe den SD Karten Support in Octoprint einfach abgeschaltet, die Klipper Konfiguration aber so belassen, wie sie ist. Damit ist alles gut bis dato.

Lieber Gruß
Holger

**Comment by thelastWallE** [comment]
Danke für die Info! Wäre theoretisch möglich ne Abfrage zu machen dafür beim speichern der Config.

Schöne Grüße,
Sven
