### ISSUE TITLE
OctoprintKlipperPlugin update error

### ISSUE THREAD

**Issue by lcha78** [thelastWallE/OctoprintKlipperPlugin#7]
Good new, Octoprint detect the new version 0.3.1 of Octoklipper and propose to update. But there is a problem in the namming somewhere : OctoprintKlipperPlugin instead of OctoPrintKlipper

![image](https://user-images.githubusercontent.com/70471286/92013619-5525e400-ed4e-11ea-8b04-862facbe9d9f.png)

The whole error text 
Updating, please wait.
/usr/local/bin/python -m pip --disable-pip-version-check install https://github.com/AliceGrey/OctoPrintKlipper/archive/0.3.1.zip --no-cache-dir
Collecting https://github.com/AliceGrey/OctoPrintKlipper/archive/0.3.1.zip
ERROR: HTTP error 404 while getting https://github.com/AliceGrey/OctoPrintKlipper/archive/0.3.1.zip
ERROR: Could not install requirement https://github.com/AliceGrey/OctoPrintKlipper/archive/0.3.1.zip because of error 404 Client Error: Not Found for url: https://github.com/AliceGrey/OctoPrintKlipper/archive/0.3.1.zip
ERROR: Could not install requirement https://github.com/AliceGrey/OctoPrintKlipper/archive/0.3.1.zip because of HTTP error 404 Client Error: Not Found for url: https://github.com/AliceGrey/OctoPrintKlipper/archive/0.3.1.zip for URL https://github.com/AliceGrey/OctoPrintKlipper/archive/0.3.1.zip
The update did not finish successfully. Please consult <code>octoprint.log</code> and <code>plugin_softwareupdate_console.log</code> for details.

**Comment by AliceGrey** [comment]
@lcha78 Issue should be resolved by https://github.com/AliceGrey/OctoprintKlipperPlugin/commit/a2291b1a3d4796c5b8861f0efc20e4ed83a3de45

I have re-done the release tag for 0.3.1. Please try it now.

Thanks!

**Comment by lcha78** [comment]
Should be OK. 
Have to wait for the next release to be sure.

**Comment by frap129** [comment]
I was able to update to 0.3.1 without running into the issue mentioned above

**Comment by AliceGrey** [comment]
Marking as resolved
