### ISSUE TITLE
Repeating errors cover screen and force reload.

### ISSUE THREAD

**Issue by charredchar** [thelastWallE/OctoprintKlipperPlugin#72]
Running OctoPi 0.18.0, OctoPrint 1.7.2 and OctoKlipper 0.3.9.
The new "feature", Popups for Errors from Klipper, floods the screen and forces the need of disconnecting OctoPrint from Klipper and a reload of the page to clear it. This particular popup is caused by my printer being turned off and Klipper stating it can not connect to it which is a very common state.
At a minimum there needs to be an option to turn off popups from OctoKlipper, preferably not have it on by default.

![image](https://user-images.githubusercontent.com/1829271/142114969-047063e6-0025-4f5e-932d-42aa488ae752.png)

**Comment by thelastWallE** [comment]
Will push a fix for it today.
edit: related : https://sciactive.com/2020/02/11/the-modalish-notification-flow/

**Comment by charredchar** [comment]
Thank you for adding the option! I also see that you introduced the modalish flow so even with it on by default you don't get flooded and it gives a chance to get into the settings to disable notifications.

This is only slightly related so I can create a new issue if you prefer but I noticed the sidebar notification now changes size. This can get pretty long with detailed messages now, would it be possible to have an option to limit the size again? I'll end up doing it through UI Customizer if not, so I don't think it is a priority.

**Comment by thelastWallE** [comment]
will add a max height setting for it.
