### ISSUE TITLE
Bed Level failure since update to 0.3.9.4

### ISSUE THREAD

**Issue by dsloyer74** [thelastWallE/OctoprintKlipperPlugin#77]
Before submitting your issue please make sure to provide the following information

About your environment:
Octoprint 1.7.2
Octopi latest official
Octoklipper 0.3.9.4
[octoprint.log](https://github.com/thelastWallE/OctoprintKlipperPlugin/files/7797176/octoprint.log)

Ran 5 successful prints and 3 successful calibration tests with no issues.  Bed Leveling will not complete or BLtouch malfunctions immediately following upgrade of Octoklipper to 0.3.9.4.  No other changes have been made to my Klipper or Octoprint config.
Update was prompted by Octoprint at login.  Prints were flawless prior to this update, very well tuned.

    An OctoPrint log file. You can access and download it in the OctoPrint settings under the "Logging" menu entry.

Thanks

**Comment by thelastWallE** [comment]
Hello. I would need the gcode from TEST2Flow calibration_24m_0.15mm_255C_PETG_CR10MAX.gcode .
Seems like there is a problem just after the probing.
```
| Recv: // probe at 427.000,225.000 is z=2.484000
| Recv: // probe at 427.000,225.000 is z=2.514000
| Recv: !! Failed to home probe: Timeout during homing
```
- Are you using an OctoKlipper macro?
- The klippy.log would be helpful here.
