### ISSUE TITLE
 Unable to open config file /home/pi/printer.cfg

### ISSUE THREAD

**Issue by 128keaton** [thelastWallE/OctoprintKlipperPlugin#84]
Environment:
* OctoPi image - Linux kernel 5.4.79-v7+
* OctoPrint v1.7.3 (latest)

[octoprint.log](https://github.com/thelastWallE/OctoprintKlipperPlugin/files/8653967/octoprint.log)

Hello, when using the latest release of your plugin from the Plugin Manager, I configured the config path to use a directory inside of my home dir. However, even after restarting Klipper, OctoPrint, etc, it will still try and use the original path `~/printer.cfg`

<img width="857" alt="Screen Shot 2022-05-09 at 12 45 27 PM" src="https://user-images.githubusercontent.com/1402918/167467248-e4f8f358-5b67-4bb7-9153-141a9514370f.png">
<img width="291" alt="Screen Shot 2022-05-09 at 12 46 16 PM" src="https://user-images.githubusercontent.com/1402918/167467421-2452637f-a574-485f-918c-b3fe98ed347b.png">

**Comment by thelastWallE** [comment]
Just some quick words here. I actually need to try a little solution i have in mind.

But it is basically that klipper is trying to load the config from the old path which is standard set from the install script of klipper.
See https://github.com/Klipper3d/klipper/blob/2c441b4502c3fb4d5199d1193475b3f2e74cac0a/scripts/install-octopi.sh#L59

We would need to change the path which is written in /etc/default/klipper and restart the klipper service afterwards.

**Comment by thelastWallE** [comment]
I will create a button in the settings which will then create a file which is modified from the original file for the klipper service and show a command which you would need to enter on the bash. This will change the file responsible for the klipper service to have the new path for the configs.
The 5 oldest servicefiles will be backuped on the data directory of octoklipper.
